### ISSUE TITLE
No project file.

### ISSUE THREAD

**Issue by ajanata** [TwistedMexi/CudaManager#1]
There isn't a project file, so building this without actually installing Visual Studio is a pain in the rear. Could you add the project file you're using, please?

**Comment by TwistedMexi** [comment]
Added. Sorry about that.

**Comment by ajanata** [comment]
Looks like app.config and a bunch of files in Properties are referenced by the project file, but are not present.

(I'm trying to get this into a buildable state so I can test a bugfix and send a pull request.)

**Comment by TwistedMexi** [comment]
I'd prefer for you to submit a bug report as I didn't intend to use github for more than allowing people to check the code.

Thanks.

**Comment by ajanata** [comment]
Kinda defeats the point, but okay...
