### ISSUE TITLE
Missing app.config and several files in the Properties directory.

### ISSUE THREAD

**Issue by ajanata** [TwistedMexi/CudaManager#2]
There are several files referenced by the project file which are not actually checked in, which makes it impossible to compile this project.

**Comment by TwistedMexi** [comment]
Do you happen to have a list of which files it's wanting? If so, I'll try to add them tonight.

**Comment by VeliV** [comment]
At least all the resources and app.config are missing.

Take a clean build from github to another folder on your computer (or better yet, another computer or virtual machine) and try to build it.

**Comment by ajanata** [comment]
Why not just check everything in from the project directory? If Visual Studio created the file, it almost certainly is referenced by the project file and is required for building.
