### ISSUE TITLE
Does not accept .bat files with an @ at the start of the line.

### ISSUE THREAD

**Issue by ajanata** [TwistedMexi/CudaManager#3]
CUDA Manager rejects .bat files when the cudaminer command's line starts with an @. This is a valid (and common) construct in batch files and should be ignored for the purposes here. I have a patch which should fix this, but without the remainder of the files required to compile the project (#2), I cannot test it.

**Comment by TwistedMexi** [comment]
Patched in V1.2. Thanks.
